---
title: "TD PERFORMANCE"
subtitile: "VIB DSC"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
---

```{r setup, include=FALSE}
pacman::p_load(tidyverse, reshape2, scales, ggthemes, plotly, ggpubr, ggalluvial,RColorBrewer, ggrepel)
df <- read.csv('TD_524_SEP.csv', sep = "|")
df <- rbind(df, read.csv('TD_524_OCT.csv', sep = "|"))
df <- rbind(df, read.csv('TD_524_NOV.csv', sep = "|"))
df <- rbind(df, read.csv('TD_524_DEC.csv', sep = "|"))
df$VALUE_DATE <- as.Date(df$VALUE_DATE, '%m/%d/%Y')
df <- df %>% mutate(MONTH = format(VALUE_DATE,'%m-%Y'))
df <- df %>% filter(OPENING_AMOUNT > 0)
T10 <- read.csv('df_HIGH_POTENTIAL_TD_ONLINE_11.csv')
T10$flag <- ifelse(T10$td_online_proba_11 >=0.5, 1, 0)
selected_t10 <- T10[T10$flag == 1,]$client_no
non_selected_t10 <- T10[T10$flag == 0,]$client_no
both_t10 <- T10$client_no
selected <- readxl::read_excel('client_list.xlsx')
selected <- selected$client_no
# head(selected)
non_selected <- read.csv('df_HIGH_POTENTIAL_TD_ONLINE_12.csv', sep = ',')
non_selected <- non_selected$client_no
# head(non_selected)
both <- c(selected, non_selected)
# head(both)
cam_date <- as.Date('23/11/2022', '%d/%m/%Y')
boths <- c(both_t10, both)
sub_df <- df %>% filter(CLIENT_NO %in% boths)
t <- sub_df %>% group_by(MONTH,CLIENT_NO) %>% arrange(VALUE_DATE, .by_group = TRUE) %>% summarise(MIN = min(VALUE_DATE))
t_ <- left_join(sub_df, t, by = c('MONTH','CLIENT_NO')) %>% mutate(NEXT = ifelse(VALUE_DATE == MIN, 0, 1))
```

Model performance {.tabset}
===================

Row
-----------------------------------------------------------------------

### Model performance

```{r}
performance <- data.frame(Month = NA,
                          Export = NA,
                          Match = NA)
performance <- rbind(performance, data.frame(Month = 'NOV 2022',
                                            Export = length(selected_t10),
                                            Match = nrow(df %>% filter(MONTH == '11-2022') %>% filter(CLIENT_NO %in% selected_t10) %>% select(CLIENT_NO) %>% unique())
                                            ))
performance <- rbind(performance, data.frame(Month = 'DEC 2022',
                                            Export = length(selected),
                                            Match = nrow(df %>% filter(MONTH == '12-2022') %>% filter(CLIENT_NO %in% selected) %>% select(CLIENT_NO) %>% unique())
                                            ))
performance <- na.omit(performance)
performance <- performance %>% mutate(Precision = Match / Export)
y_max <- max(performance %>% select(is.numeric))
scaleRight <- 100 / y_max
ggplot(melt(performance %>% select(-Precision) %>% mutate(Month = factor(Month, levels = c('NOV 2022', 'DEC 2022')))), aes(x = Month)) +
    geom_bar(aes(y = value, fill = variable, color = variable),  stat = 'identity', position = "dodge") +
    geom_point(data = performance, aes( y = Precision * 100 / scaleRight, group = 1, color = 'Precision'), size = 3) +
    geom_line(data = performance, aes( y = Precision * 100 / scaleRight, group = 1, color = 'Precision'), size = 1) +
    geom_text(data = performance, aes(y = (Precision * 100 + 5) / scaleRight , label = paste(round(Precision,2)*100, '%'), color = 'Precision'),show.legend=F, size = 6) +
    scale_y_continuous(labels = comma, expand = expansion(mult = c(0,.05)),
                    sec.axis = sec_axis(~.*scaleRight, name = "Precision (%)",
                                        breaks=seq(0,100,10))) +
    theme_wsj() +
    guides(color = guide_legend(nrow = 1), fill="none") +
    labs( y="# Cust", x="Month") +
    theme(axis.text=element_text(size=12), legend.position = 'none',
        axis.title=element_text(size=14,face="bold"),
        legend.title=element_blank(), plot.title = element_text(face="bold", size = 20),
        panel.background = element_rect(fill = 'white'), plot.background = element_rect(fill = 'white'),legend.background = element_rect(fill = 'white'))
```

###

Row
-----------------------------------------------------------------------

### Average tenor

```{r}
tmp <- sub_df %>% filter(VALUE_DATE < cam_date) %>% filter(CLIENT_NO %in% boths) %>%
                group_by(MONTH) %>% 
                summarise(Tenor = mean(TERM_BY_DAY, na.rm = TRUE))
tmp_ <- sub_df %>% filter(VALUE_DATE >= cam_date) %>% filter(CLIENT_NO %in% c(selected_t10, selected)) %>%
                group_by(MONTH) %>% 
                summarise(Tenor = mean(TERM_BY_DAY, na.rm = TRUE))
tmp__ <- sub_df %>% filter(VALUE_DATE >= cam_date) %>% filter(CLIENT_NO %in% c(non_selected_t10, non_selected)) %>%
                group_by(MONTH) %>% 
                summarise(Tenor = mean(TERM_BY_DAY, na.rm = TRUE))
ggplot() + 
geom_line(data = tmp , aes(x = MONTH, y = Tenor, group = 1, color = 'Before campaign'), size = 1) +
geom_point(data = tmp , aes(x = MONTH, y = Tenor, group = 1, color = 'Before campaign'), size = 5) +
geom_line(data = tmp__ , aes(x = MONTH, y = Tenor, group = 1, color = 'During campaign-Non-selected'), size = 1) +
geom_point(data = tmp__ , aes(x = MONTH, y = Tenor, group = 1, color = 'During campaign-Non-selected'), size = 5) +
geom_line(data = tmp_ , aes(x = MONTH, y = Tenor, group = 1, color = 'During campaign-Selected'), size = 1) +
geom_point(data = tmp_ , aes(x = MONTH, y = Tenor, group = 1, color = 'During campaign-Selected'), size = 5) +
scale_y_continuous(labels = comma) +
labs(x = 'Month', y = 'Average tenor (days)', caption = 'Based on predicted segment only') +
theme_wsj() +
scale_color_manual(values = c('#FFC074','#B6C867','#01937C')) + 
# theme(legend.title = element_blank(), legend.position = 'bottom', axis.title.y= element_text())
theme(legend.title = element_blank(), legend.position = 'bottom',axis.title.y= element_text(), axis.text=element_text(size=12),
      axis.title=element_text(size=14,face="bold"), plot.caption = element_text(size = 10, face = 'italic'),
      legend.text = element_text(size = 6),panel.background = element_rect(fill = 'white'), plot.background = element_rect(fill = 'white'),
      legend.background = element_rect(fill = 'white'))
```

### Average tenor per cust

```{r}
tmp <- sub_df %>% filter(VALUE_DATE < cam_date) %>% filter(CLIENT_NO %in% boths) %>%
                group_by(MONTH, CLIENT_NO) %>% 
                summarise(Tenor = sum(TERM_BY_DAY, na.rm = TRUE)) %>%
                group_by(MONTH) %>%
                summarise(Tenor = mean(Tenor, na.rm = TRUE))
tmp_ <- sub_df %>% filter(VALUE_DATE >= cam_date) %>% filter(CLIENT_NO %in% c(selected_t10, selected)) %>%
                group_by(MONTH, CLIENT_NO) %>% 
                summarise(Tenor = sum(TERM_BY_DAY, na.rm = TRUE)) %>%
                group_by(MONTH) %>%
                summarise(Tenor = mean(Tenor, na.rm = TRUE))
tmp__ <- sub_df %>% filter(VALUE_DATE >= cam_date) %>% filter(CLIENT_NO %in% c(non_selected_t10, non_selected)) %>%
                group_by(MONTH, CLIENT_NO) %>% 
                summarise(Tenor = sum(TERM_BY_DAY, na.rm = TRUE)) %>%
                group_by(MONTH) %>%
                summarise(Tenor = mean(Tenor, na.rm = TRUE))
ggplot() + 
geom_line(data = tmp , aes(x = MONTH, y = Tenor, group = 1, color = 'Before campaign'), size = 1) +
geom_point(data = tmp , aes(x = MONTH, y = Tenor, group = 1, color = 'Before campaign'), size = 5) +
geom_line(data = tmp__ , aes(x = MONTH, y = Tenor, group = 1, color = 'During campaign-Non-selected'), size = 1) +
geom_point(data = tmp__ , aes(x = MONTH, y = Tenor, group = 1, color = 'During campaign-Non-selected'), size = 5) +
geom_line(data = tmp_ , aes(x = MONTH, y = Tenor, group = 1, color = 'During campaign-Selected'), size = 1) +
geom_point(data = tmp_ , aes(x = MONTH, y = Tenor, group = 1, color = 'During campaign-Selected'), size = 5) +
scale_y_continuous(labels = comma) +
labs(x = 'Month', y = 'Average tenor per cust (days)') +
theme_wsj() +
scale_color_manual(values = c('#FFC074','#B6C867','#01937C')) + 
# theme(legend.title = element_blank(), legend.position = 'bottom', axis.title.y= element_text())
theme(legend.position = 'none',axis.title.y= element_text(), axis.text=element_text(size=12),axis.title=element_text(size=14,face="bold"),
      panel.background = element_rect(fill = 'white'), plot.background = element_rect(fill = 'white'))
```

Row
-----------------------------------------------------------------------


### Average opening balance

```{r}
tmp <- sub_df %>% filter(VALUE_DATE < cam_date) %>% filter(CLIENT_NO %in% boths) %>%
                group_by(MONTH) %>% 
                summarise(AMT = mean(OPENING_AMOUNT, na.rm = TRUE))
tmp_ <- sub_df %>% filter(VALUE_DATE >= cam_date) %>% filter(CLIENT_NO %in% c(selected_t10, selected)) %>%
                group_by(MONTH) %>% 
                summarise(AMT = mean(OPENING_AMOUNT, na.rm = TRUE))
tmp__ <- sub_df %>% filter(VALUE_DATE >= cam_date) %>% filter(CLIENT_NO %in% c(non_selected_t10, non_selected)) %>%
                group_by(MONTH) %>% 
                summarise(AMT = mean(OPENING_AMOUNT, na.rm = TRUE))
ggplot() + 
geom_line(data = tmp , aes(x = MONTH, y = AMT/10^6, group = 1, color = 'Before campaign'), size = 1) +
geom_point(data = tmp , aes(x = MONTH, y = AMT/10^6, group = 1, color = 'Before campaign'), size = 5) +
geom_line(data = tmp__ , aes(x = MONTH, y = AMT/10^6, group = 1, color = 'During campaign-Non-selected'), size = 1) +
geom_point(data = tmp__ , aes(x = MONTH, y = AMT/10^6, group = 1, color = 'During campaign-Non-selected'), size = 5) +
geom_line(data = tmp_ , aes(x = MONTH, y = AMT/10^6, group = 1, color = 'During campaign-Selected'), size = 1) +
geom_point(data = tmp_ , aes(x = MONTH, y = AMT/10^6, group = 1, color = 'During campaign-Selected'), size = 5) +
scale_y_continuous(labels = comma) +
labs(x = 'Month', y = 'Average outstanding balance (M)') +
theme_wsj() +
scale_color_manual(values = c('#FFC074','#B6C867','#01937C')) + 
# theme(legend.title = element_blank(), legend.position = 'bottom', axis.title.y= element_text())
theme(legend.title = element_blank(), legend.position = 'bottom',axis.title.y= element_text(), axis.text=element_text(size=12),
      axis.title=element_text(size=14,face="bold"), plot.caption = element_text(size = 10, face = 'italic'),
      legend.text = element_text(size = 6),panel.background = element_rect(fill = 'white'), plot.background = element_rect(fill = 'white'),
      legend.background = element_rect(fill = 'white'))
```

### Average opening balance per cust

```{r}
tmp <- sub_df %>% filter(VALUE_DATE < cam_date) %>% filter(CLIENT_NO %in% boths) %>%
                group_by(MONTH, CLIENT_NO) %>% 
                summarise(AMT = sum(OPENING_AMOUNT, na.rm = TRUE)) %>%
                group_by(MONTH) %>%
                summarise(AMT = mean(AMT, na.rm = TRUE)/10^6)
tmp_ <- sub_df %>% filter(VALUE_DATE >= cam_date) %>% filter(CLIENT_NO %in% c(selected_t10, selected)) %>%
                group_by(MONTH, CLIENT_NO) %>% 
                summarise(AMT = sum(OPENING_AMOUNT, na.rm = TRUE)) %>%
                group_by(MONTH) %>%
                summarise(AMT = mean(AMT, na.rm = TRUE)/10^6)
tmp__ <- sub_df %>% filter(VALUE_DATE >= cam_date) %>% filter(CLIENT_NO %in% c(non_selected_t10, non_selected)) %>%
                group_by(MONTH, CLIENT_NO) %>% 
                summarise(AMT = sum(OPENING_AMOUNT, na.rm = TRUE)) %>%
                group_by(MONTH) %>%
                summarise(AMT = mean(AMT, na.rm = TRUE)/10^6)
ggplot() + 
geom_line(data = tmp , aes(x = MONTH, y = AMT, group = 1, color = 'Before campaign'), size = 1) +
geom_point(data = tmp , aes(x = MONTH, y = AMT, group = 1, color = 'Before campaign'), size = 5) +
geom_line(data = tmp__ , aes(x = MONTH, y = AMT, group = 1, color = 'During campaign-Non-selected'), size = 1) +
geom_point(data = tmp__ , aes(x = MONTH, y = AMT, group = 1, color = 'During campaign-Non-selected'), size = 5) +
geom_line(data = tmp_ , aes(x = MONTH, y = AMT, group = 1, color = 'During campaign-Selected'), size = 1) +
geom_point(data = tmp_ , aes(x = MONTH, y = AMT, group = 1, color = 'During campaign-Selected'), size = 5) +
scale_y_continuous(labels = comma) +
labs(x = 'Month', y = 'Average outstanding balance per cust (M)') +
theme_wsj() +
scale_color_manual(values = c('#FFC074','#B6C867','#01937C')) + 
theme(legend.position = 'none',axis.title.y= element_text(), axis.text=element_text(size=12),axis.title=element_text(size=14,face="bold"),
      panel.background = element_rect(fill = 'white'), plot.background = element_rect(fill = 'white'))
```

Row
-----------------------------------------------------------------------

### Average rollover ratio

```{r}
tmp <- sub_df %>% filter(VALUE_DATE < cam_date) %>% filter(CLIENT_NO %in% boths) %>%
                group_by(MONTH) %>%
                summarise(ARR = mean(ROLLOVER_FLAG, na.rm = TRUE) * 100)
tmp_ <- sub_df %>% filter(VALUE_DATE >= cam_date) %>% filter(CLIENT_NO %in% c(selected_t10, selected)) %>%
                group_by(MONTH) %>% 
                summarise(ARR = mean(ROLLOVER_FLAG, na.rm = TRUE) * 100)
tmp__ <- sub_df %>% filter(VALUE_DATE >= cam_date) %>% filter(CLIENT_NO %in% c(non_selected_t10, non_selected)) %>%
                group_by(MONTH) %>% 
                summarise(ARR = mean(ROLLOVER_FLAG, na.rm = TRUE) * 100)
ggplot() + 
geom_line(data = tmp , aes(x = MONTH, y = ARR, group = 1, color = 'Before campaign'), size = 1) +
geom_point(data = tmp , aes(x = MONTH, y = ARR, group = 1, color = 'Before campaign'), size = 5) +
geom_line(data = tmp__ , aes(x = MONTH, y = ARR, group = 1, color = 'During campaign-Non-selected'), size = 1) +
geom_point(data = tmp__ , aes(x = MONTH, y = ARR, group = 1, color = 'During campaign-Non-selected'), size = 5) +
geom_line(data = tmp_ , aes(x = MONTH, y = ARR, group = 1, color = 'During campaign-Selected'), size = 1) +
geom_point(data = tmp_ , aes(x = MONTH, y = ARR, group = 1, color = 'During campaign-Selected'), size = 5) +
scale_y_continuous(labels = comma) +
labs(x = 'Month', y = 'Average rollover ratio (%)') +
theme_wsj() +
scale_color_manual(values = c('#FFC074','#B6C867','#01937C')) + 
# theme(legend.title = element_blank(), legend.position = 'bottom', axis.title.y= element_text())
theme(legend.title = element_blank(), legend.position = 'bottom',axis.title.y= element_text(), axis.text=element_text(size=12),
      axis.title=element_text(size=14,face="bold"), plot.caption = element_text(size = 10, face = 'italic'),
      legend.text = element_text(size = 6),panel.background = element_rect(fill = 'white'), plot.background = element_rect(fill = 'white'),
      legend.background = element_rect(fill = 'white'))
```

### Average rollover ratio per cust 

```{r}
tmp <- sub_df %>% filter(VALUE_DATE < cam_date) %>% filter(CLIENT_NO %in% boths) %>%
                group_by(MONTH, CLIENT_NO) %>%
                summarise(ARR = mean(ROLLOVER_FLAG, na.rm = TRUE) * 100) %>%
                group_by(MONTH) %>%
                summarise(ARR = mean(ARR, na.rm = TRUE))
tmp_ <- sub_df %>% filter(VALUE_DATE >= cam_date) %>% filter(CLIENT_NO %in% c(selected_t10, selected)) %>%
                group_by(MONTH, CLIENT_NO) %>%
                summarise(ARR = mean(ROLLOVER_FLAG, na.rm = TRUE) * 100) %>%
                group_by(MONTH) %>%
                summarise(ARR = mean(ARR, na.rm = TRUE))
tmp__ <- sub_df %>% filter(VALUE_DATE >= cam_date) %>% filter(CLIENT_NO %in% c(non_selected_t10, non_selected)) %>%
                group_by(MONTH, CLIENT_NO) %>%
                summarise(ARR = mean(ROLLOVER_FLAG, na.rm = TRUE) * 100) %>%
                group_by(MONTH) %>%
                summarise(ARR = mean(ARR, na.rm = TRUE))
ggplot() + 
geom_line(data = tmp , aes(x = MONTH, y = ARR, group = 1, color = 'Before campaign'), size = 1) +
geom_point(data = tmp , aes(x = MONTH, y = ARR, group = 1, color = 'Before campaign'), size = 5) +
geom_line(data = tmp__ , aes(x = MONTH, y = ARR, group = 1, color = 'During campaign-Non-selected'), size = 1) +
geom_point(data = tmp__ , aes(x = MONTH, y = ARR, group = 1, color = 'During campaign-Non-selected'), size = 5) +
geom_line(data = tmp_ , aes(x = MONTH, y = ARR, group = 1, color = 'During campaign-Selected'), size = 1) +
geom_point(data = tmp_ , aes(x = MONTH, y = ARR, group = 1, color = 'During campaign-Selected'), size = 5) +
scale_y_continuous(labels = comma) +
labs(x = 'Month', y = 'Average rollover ratio per cust (%)') +
theme_wsj() +
scale_color_manual(values = c('#FFC074','#B6C867','#01937C')) + 
# theme(legend.title = element_blank(), legend.position = 'bottom', axis.title.y= element_text())
theme(legend.title = element_blank(), legend.position = 'bottom',axis.title.y= element_text(), axis.text=element_text(size=12),
      axis.title=element_text(size=14,face="bold"), plot.caption = element_text(size = 10, face = 'italic'),
      legend.text = element_text(size = 6),panel.background = element_rect(fill = 'white'), plot.background = element_rect(fill = 'white'),
      legend.background = element_rect(fill = 'white'))
```

Row
-----------------------------------------------------------------------

### Average elapse on next opening TD

```{r}
tmp <- t_ %>% filter(VALUE_DATE < cam_date) %>% filter(CLIENT_NO %in% boths) %>% filter(NEXT == 1) %>%
                group_by(MONTH, CLIENT_NO) %>%
                arrange(VALUE_DATE, .by_group = TRUE) %>% 
                mutate(LAG_VALUE_DATE = lag(VALUE_DATE)) %>% 
                mutate(DIFF = as.numeric(VALUE_DATE - LAG_VALUE_DATE)) %>% 
                group_by(MONTH) %>% summarise(DIFF = mean(DIFF, na.rm = TRUE))

tmp_ <- t_ %>% filter(VALUE_DATE >= cam_date) %>% filter(CLIENT_NO %in% c(selected_t10, selected)) %>% filter(NEXT == 1) %>%
                group_by(MONTH, CLIENT_NO) %>%
                arrange(VALUE_DATE, .by_group = TRUE) %>% 
                mutate(LAG_VALUE_DATE = lag(VALUE_DATE)) %>% 
                mutate(DIFF = as.numeric(VALUE_DATE - LAG_VALUE_DATE)) %>% 
                group_by(MONTH) %>% summarise(DIFF = mean(DIFF, na.rm = TRUE))
tmp__ <- t_ %>% filter(VALUE_DATE >= cam_date) %>% filter(CLIENT_NO %in% c(non_selected_t10, non_selected)) %>% filter(NEXT == 1) %>%
                group_by(MONTH, CLIENT_NO) %>%
                arrange(VALUE_DATE, .by_group = TRUE) %>% 
                mutate(LAG_VALUE_DATE = lag(VALUE_DATE)) %>% 
                mutate(DIFF = as.numeric(VALUE_DATE - LAG_VALUE_DATE)) %>% 
                group_by(MONTH) %>% summarise(DIFF = mean(DIFF, na.rm = TRUE))


ggplot() + 
geom_line(data = tmp , aes(x = MONTH, y = DIFF, group = 1, color = 'Before campaign'), size = 1) +
geom_point(data = tmp , aes(x = MONTH, y = DIFF, group = 1, color = 'Before campaign'), size = 5) +
geom_line(data = tmp__ , aes(x = MONTH, y = DIFF, group = 1, color = 'During campaign-Non-selected'), size = 1) +
geom_point(data = tmp__ , aes(x = MONTH, y = DIFF, group = 1, color = 'During campaign-Non-selected'), size = 5) +
geom_line(data = tmp_ , aes(x = MONTH, y = DIFF, group = 1, color = 'During campaign-Selected'), size = 1) +
geom_point(data = tmp_ , aes(x = MONTH, y = DIFF, group = 1, color = 'During campaign-Selected'), size = 5) +
labs(x = 'Month', y = 'Average elapse (days)') +
theme_wsj() +
scale_color_manual(values = c('#FFC074','#B6C867','#01937C')) + 
theme(legend.position = 'none',axis.title.y= element_text(), axis.text=element_text(size=12),axis.title=element_text(size=14,face="bold"),
      panel.background = element_rect(fill = 'white'), plot.background = element_rect(fill = 'white'))
```

### Average elapse on next opening TD per cust 

```{r}
tmp_func <- function(vec) {
    if (length(vec) > 1){
        return(as.numeric(mean(diff(vec[order(vec)]))))
    } else {
        return(NA)
    }
}
tmp <- t_ %>% filter(VALUE_DATE < cam_date) %>% filter(CLIENT_NO %in% boths) %>% filter(NEXT == 1) %>%
                group_by(MONTH, CLIENT_NO) %>%
                arrange(VALUE_DATE, .by_group = TRUE) %>% 
                summarise(Dif = tmp_func(VALUE_DATE)) %>%
                group_by(MONTH) %>% summarise(ADif = mean(Dif, na.rm = TRUE))

tmp_ <- t_ %>% filter(VALUE_DATE >= cam_date) %>% filter(CLIENT_NO %in% c(selected_t10, selected)) %>% filter(NEXT == 1) %>%
                group_by(MONTH, CLIENT_NO) %>%
                arrange(VALUE_DATE, .by_group = TRUE) %>% 
                summarise(Dif = tmp_func(VALUE_DATE)) %>%
                group_by(MONTH) %>% summarise(ADif = mean(Dif, na.rm = TRUE))
tmp__ <- t_ %>% filter(VALUE_DATE >= cam_date) %>% filter(CLIENT_NO %in% c(non_selected_t10, non_selected)) %>% filter(NEXT == 1) %>%
                group_by(MONTH, CLIENT_NO) %>%
                arrange(VALUE_DATE, .by_group = TRUE) %>% 
                summarise(Dif = tmp_func(VALUE_DATE)) %>%
                group_by(MONTH) %>% summarise(ADif = mean(Dif, na.rm = TRUE))


ggplot() + 
geom_line(data = tmp , aes(x = MONTH, y = ADif, group = 1, color = 'Before campaign'), size = 1) +
geom_point(data = tmp , aes(x = MONTH, y = ADif, group = 1, color = 'Before campaign'), size = 5) +
geom_line(data = tmp__ , aes(x = MONTH, y = ADif, group = 1, color = 'During campaign-Non-selected'), size = 1) +
geom_point(data = tmp__ , aes(x = MONTH, y = ADif, group = 1, color = 'During campaign-Non-selected'), size = 5) +
geom_line(data = tmp_ , aes(x = MONTH, y = ADif, group = 1, color = 'During campaign-Selected'), size = 1) +
geom_point(data = tmp_ , aes(x = MONTH, y = ADif, group = 1, color = 'During campaign-Selected'), size = 5) +
labs(x = 'Month', y = 'Average elapse (days)') +
theme_wsj() +
scale_color_manual(values = c('#FFC074','#B6C867','#01937C')) + 
theme(legend.position = 'none',axis.title.y= element_text(), axis.text=element_text(size=12),axis.title=element_text(size=14,face="bold"),
      panel.background = element_rect(fill = 'white'), plot.background = element_rect(fill = 'white'))
```

Row
-----------------------------------------------------------------------
### Average TD balance on next opening TD

```{r}
tmp <- t_ %>% filter(VALUE_DATE < cam_date) %>% filter(CLIENT_NO %in% boths) %>% filter(NEXT == 1) %>%
                group_by(MONTH) %>% 
                summarise(AMT = mean(OPENING_AMOUNT, na.rm = TRUE)/10^6)

tmp_ <- t_ %>% filter(VALUE_DATE >= cam_date) %>% filter(CLIENT_NO %in% c(selected_t10, selected)) %>% filter(NEXT == 1) %>%
                group_by(MONTH) %>% 
                summarise(AMT = mean(OPENING_AMOUNT, na.rm = TRUE)/10^6)
tmp__ <- t_ %>% filter(VALUE_DATE >= cam_date) %>% filter(CLIENT_NO %in% c(non_selected_t10, non_selected)) %>% filter(NEXT == 1) %>%
                group_by(MONTH) %>% 
                summarise(AMT = mean(OPENING_AMOUNT, na.rm = TRUE)/10^6)


ggplot() + 
geom_line(data = tmp , aes(x = MONTH, y = AMT, group = 1, color = 'Before campaign'), size = 1) +
geom_point(data = tmp , aes(x = MONTH, y = AMT, group = 1, color = 'Before campaign'), size = 5) +
geom_line(data = tmp__ , aes(x = MONTH, y = AMT, group = 1, color = 'During campaign-Non-selected'), size = 1) +
geom_point(data = tmp__ , aes(x = MONTH, y = AMT, group = 1, color = 'During campaign-Non-selected'), size = 5) +
geom_line(data = tmp_ , aes(x = MONTH, y = AMT, group = 1, color = 'During campaign-Selected'), size = 1) +
geom_point(data = tmp_ , aes(x = MONTH, y = AMT, group = 1, color = 'During campaign-Selected'), size = 5) +
labs(x = 'Month', y = 'Average TD balance on next opening TD (M)') +
theme_wsj() +
scale_color_manual(values = c('#FFC074','#B6C867','#01937C')) + 
theme(legend.position = 'none',axis.title.y= element_text(), axis.text=element_text(size=12),axis.title=element_text(size=14,face="bold"),
      panel.background = element_rect(fill = 'white'), plot.background = element_rect(fill = 'white'))
```

### Average TD balance on next opening TD per cust 

```{r}
tmp <- t_ %>% filter(VALUE_DATE < cam_date) %>% filter(CLIENT_NO %in% boths) %>% filter(NEXT == 1) %>%
                group_by(MONTH, CLIENT_NO) %>% 
                summarise(AMT = sum(OPENING_AMOUNT, na.rm = TRUE)/10^6) %>%
                group_by(MONTH) %>%
                summarise(AMT = mean(AMT, na.rm = TRUE))

tmp_ <- t_ %>% filter(VALUE_DATE >= cam_date) %>% filter(CLIENT_NO %in% c(selected_t10, selected)) %>% filter(NEXT == 1) %>%
                group_by(MONTH, CLIENT_NO) %>% 
                summarise(AMT = sum(OPENING_AMOUNT, na.rm = TRUE)/10^6) %>%
                group_by(MONTH) %>%
                summarise(AMT = mean(AMT, na.rm = TRUE))
tmp__ <- t_ %>% filter(VALUE_DATE >= cam_date) %>% filter(CLIENT_NO %in% c(non_selected_t10, non_selected)) %>% filter(NEXT == 1) %>%
                group_by(MONTH, CLIENT_NO) %>% 
                summarise(AMT = sum(OPENING_AMOUNT, na.rm = TRUE)/10^6) %>%
                group_by(MONTH) %>%
                summarise(AMT = mean(AMT, na.rm = TRUE))


ggplot() + 
geom_line(data = tmp , aes(x = MONTH, y = AMT, group = 1, color = 'Before campaign'), size = 1) +
geom_point(data = tmp , aes(x = MONTH, y = AMT, group = 1, color = 'Before campaign'), size = 5) +
geom_line(data = tmp__ , aes(x = MONTH, y = AMT, group = 1, color = 'During campaign-Non-selected'), size = 1) +
geom_point(data = tmp__ , aes(x = MONTH, y = AMT, group = 1, color = 'During campaign-Non-selected'), size = 5) +
geom_line(data = tmp_ , aes(x = MONTH, y = AMT, group = 1, color = 'During campaign-Selected'), size = 1) +
geom_point(data = tmp_ , aes(x = MONTH, y = AMT, group = 1, color = 'During campaign-Selected'), size = 5) +
labs(x = 'Month', y = 'Average TD balance on next opening TD per cust (M)') +
theme_wsj() +
scale_color_manual(values = c('#FFC074','#B6C867','#01937C')) + 
theme(legend.position = 'none',axis.title.y= element_text(), axis.text=element_text(size=12),axis.title=element_text(size=14,face="bold"),
      panel.background = element_rect(fill = 'white'), plot.background = element_rect(fill = 'white'))
```

